use_frameworks!

platform :ios, '9.0'

target 'SSWebView_Example' do
  pod 'SSWebView', :path => '../'

  target 'SSWebView_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
